Perform an appropriate hypothesis test to determine the p-value, and hence result, of whether to reject or fail to reject the null hypothesis that the *mean number of goals scored in women's international soccer matches is the same as men's*. Use a **10% significance level**.

For this analysis, you'll use Official `FIFA World Cup` matches since `2002-01-01`, and you'll also assume that each match is fully independent, i.e., team form is ignored.

The p-value and the result of the test must be stored in a dictionary called `result_dict` in the form:

`result_dict = {"p_val": p_val, "result": result}`

where `p_val` is the p-value and `result` is either the string `"fail to reject"` or `"reject"`, depending on the result of the test.

The question trying to determine the answer to is:

> Are more goals scored in women's international soccer matches than men's?

Assuming a**10% significance level**, and use the following null and alternative hypotheses:

$H_0$ : The mean number of goals scored in women's international soccer matches is the same as men's.

$H_A$ : The mean number of goals scored in women's international soccer matches is greater than men's.

### Steps:
1. Exploratory Data analysis
2. Filtering the data
3. Choosing the correct hypothesis test
4. Performing the hypothesis test
5. Interpreting the results of the hypothesis test

#### Exploratory Data Analysis

In [1]:
import pandas as pd

In [2]:
men_df = pd.read_csv('csv_files/men_results.csv')
men_df.head()

,Unnamed: 0,date,home_team,away_team,home_score,away_score,tournament
0,0,1872-11-30,Scotland,England,0,0,Friendly
1,1,1873-03-08,England,Scotland,4,2,Friendly
2,2,1874-03-07,Scotland,England,2,1,Friendly
3,3,1875-03-06,England,Scotland,2,2,Friendly
4,4,1876-03-04,Scotland,England,3,0,Friendly

In [3]:
women_df = pd.read_csv('csv_files/women_results.csv')
women_df.head()

,Unnamed: 0,date,home_team,away_team,home_score,away_score,tournament
0,0,1969-11-01,Italy,France,1,0,Euro
1,1,1969-11-01,Denmark,England,4,3,Euro
2,2,1969-11-02,England,France,2,0,Euro
3,3,1969-11-02,Italy,Denmark,3,1,Euro
4,4,1975-08-25,Thailand,Australia,3,2,AFC Championship

In [4]:
print('Men')
print(men_df.info())
print('-' * 20)
print('Women')
print(women_df.info())

Men
<class 'pandas.DataFrame'>
RangeIndex: 44353 entries, 0 to 44352
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  44353 non-null  int64
 1   date        44353 non-null  str
 2   home_team   44353 non-null  str
 3   away_team   44353 non-null  str
 4   home_score  44353 non-null  int64
 5   away_score  44353 non-null  int64
 6   tournament  44353 non-null  str
dtypes: int64(3), str(4)
memory usage: 2.4 MB
None
--------------------
Women
<class 'pandas.DataFrame'>
RangeIndex: 4884 entries, 0 to 4883
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  4884 non-null   int64
 1   date        4884 non-null   str
 2   home_team   4884 non-null   str
 3   away_team   4884 non-null   str
 4   home_score  4884 non-null   int64
 5   away_score  4884 non-null   int64
 6   tournament  4884 non-null   str
dtypes: int64(3), str(4)
memory usage: 267.2 KB
None

In [5]:
men_df['tournament'].unique()

<StringArray>
[                                  'Friendly',
                  'British Home Championship',
                       'Évence Coppée Trophy',
                                'Copa Lipton',
                                'Copa Newton',
                'Copa Premio Honor Argentino',
                 'Copa Premio Honor Uruguayo',
                                  'Copa Roca',
                               'Copa América',
                    'Copa Chevallier Boutell',
 ...
 'African Nations Championship qualification',
                      'Atlantic Heritage Cup',
            'Inter Games Football Tournament',
                    'CONCACAF Nations League',
                          'Three Nations Cup',
                      'Mahinda Rajapaksa Cup',
                                 'Navruz Cup',
                 'CONIFA Africa Football Cup',
          'CONIFA South America Football Cup',
                   'MSG Prime Minister's Cup']
Length: 141, dtype: str